### ISSUE TITLE
Holmquist data hook needs work

### ISSUE THREAD

**Issue by HolmquistJ** [Smithsonian/CCRCN-Data-Library#2]
This data hook is incomplete. Although it is highly compliant, this data hook, this dataset is not totally in keeping with controlled vocabulary. It would be great to have functions to convert things like species codes, impact codes, salinity codes, and GPS data quality codes, to common plain language.

**Comment by mlonneman** [comment]
I believe the data hook should also convert Crooks_et_al_2013 to Crooks_et_al_2014. Unless I'm mistaken, the Crooks data is associated with:

Crooks, S. et al. Coastal Blue Carbon Opportunity Assessment for the Snohomish Estuary: The Climate Benefits of Estuary Restoration. (Environmental Science Associates, Western Washington University, EarthCorps, and Restore America’s Estuaries, 2014).

The study ID needs to match the ID in the bibtex file in order to be included in the downloaded bib in the map app.
